# Библиотека BLAS

Полезные ссылки:

https://docs.scipy.org/doc/scipy/reference/linalg.blas.html

https://www.math.utah.edu/software/lapack/#generalinformation

https://www.netlib.org/blas/

https://www.netlib.org/lapack/

Последние две ссылки могут не открываться без vpn

In [1]:
from scipy.linalg import blas
import numpy as np
import scipy as sp

In [2]:
n = 3
A = np.array([[1,2,3],[4,5,6],[7,8,9]])
B = np.array([[1,2,3],[4,5,6],[7,8,9]], order = 'F')

In [3]:
for cell in A.flatten():
    print(cell, end=' ')

print('\n')
    
for cell in B.flatten():
    print(cell, end=' ')

1 2 3 4 5 6 7 8 9 

1 2 3 4 5 6 7 8 9 

In [4]:
for x in np.nditer(A):
    print(x, end=' ')

1 2 3 4 5 6 7 8 9 

In [5]:
for x in np.nditer(B):
    print(x, end=' ')

1 4 7 2 5 8 3 6 9 

In [6]:
n = 2000
A = np.array(np.random.randn(n,n), order='F')
B = np.array(np.random.randn(n,n), order='F')

In [7]:
C_np = A @ B # numpy  C = A * B
C_blas = blas.dgemm(1.0, A, B) # BLAS C = A * B
np.linalg.norm(C_np - C_blas)

5.184653607576806e-12

In [8]:
%timeit C_np = np.matmul(A,B) # numpy

112 ms ± 3.16 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [9]:
%timeit C_np = A @ B

110 ms ± 4.53 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [10]:
%timeit C_blas = blas.dgemm(1.0, A, B) # blas

105 ms ± 6.31 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
n = 4096
A = np.array(np.random.randn(n,n))
B = np.array(np.random.randn(n,n))

In [12]:
C_blas = blas.dgemm(1.0, A, B)
print(C_blas)

[[  30.15592205  -26.83170904   19.98015931 ...   18.80840001
    -2.97181531 -117.00181888]
 [  76.37609178  -77.84872261   13.07061174 ...  -21.47922237
   -11.31987588   21.06175708]
 [  -6.70296031  -41.18773739   -8.13983656 ...   23.16366639
    16.66321951  116.43332744]
 ...
 [  58.74466179  -41.41994006   82.20567841 ...  -59.21648623
   -63.22758962   -1.37172595]
 [ -60.12729292  -64.1289711    -0.35486518 ...  -93.11950042
    34.55566781  -44.8612514 ]
 [ -33.56258098  -55.73436905  -77.55786191 ...  142.94651467
    75.33365468  125.60432164]]


In [13]:
def MatrMul(A,B,n):
    
    result = np.zeros((n,n))
    for i in range(n):  
        for j in range(n):
            for k in range(len(B)):
                result[i][j] += A[i][k] * B[k][j]
                
    return result

In [14]:
A = np.array([[1,1],[1,2]], order = 'F')
B = np.array([[2,-1],[0,1]], order = 'F')
C = MatrMul(A,B,2)
print(A)
print(B)
print(C)

[[1 1]
 [1 2]]
[[ 2 -1]
 [ 0  1]]
[[2. 0.]
 [2. 1.]]


In [15]:
n = 200
A = np.array(np.random.randn(n,n), order = 'F')
B = np.array(np.random.randn(n,n), order = 'F')


Попробуйте убрать *order = 'F'* и сравните время 

In [16]:
%timeit C_blas = blas.dgemm(1.0, A, B) # blas

344 µs ± 20 µs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)


In [18]:
%timeit C_our = MatrMul(A,B,n) # our

KeyboardInterrupt: 

**Названия функций в BLAS и LAPACK**

blas.<точность><имя><объкты>

<точность>:

s: single precision float

d: double precision float

c: single precision complex float

z: double precision complex float


<имя> - тип операции или матрицы 

<объкты> - используемые объекты или информация об операции

Пример:
dgemm = d + ge + mm 
d - double precision, ge - general matrix, mm - matrix multiplication

# BLAS Level 1

Операции вектор-вектор, число-вектор

**_axpy** - операция вычисления *ax + y* (x,y - векторы, a - скаляр)

**_dot** - скалярное произведение

**_nrm2** - евклидова норма

## _axpy

In [50]:
n = 1000
x = np.random.rand(n)
y = np.random.rand(n)

z = blas.daxpy(x, y, a=1.0)
xx = blas.ddot(x, x)
x2 = blas.dnrm2(x)
np.sqrt(xx) - x2

0.0

In [30]:
x = np.array([1,2,3])
y = np.array([1,1,1])    
z = blas.daxpy(x, y, a=1.0)
print(z)

[2. 3. 4.]


In [31]:
x + y

array([2, 3, 4])

In [32]:
x = np.array([1,2,3])
y = np.array([[1],[1],[1]])    
z = blas.daxpy(x, y, a=2.0)
print(z)

[[3.]
 [5.]
 [7.]]


In [33]:
x + y

array([[2, 3, 4],
       [2, 3, 4],
       [2, 3, 4]])

In [34]:
x = np.array([[1,2,3],[-1,-2,-3.0]]) # bag, look at the print(x)
y = blas.dscal(2.0,x[0])
print(y)
print(x)

[2. 4. 6.]
[[ 2.  4.  6.]
 [-1. -2. -3.]]


In [129]:
x = np.array([[1,2,3],[-1,-2,-3]]) # bag, look at the print(x)
y = blas.dscal(2,x[0])
print(y)
print(x)

[2. 4. 6.]
[[ 1  2  3]
 [-1 -2 -3]]


In [155]:
x = [[1.1,2.2,3],[-1,-2.0,-3.0]]
y = blas.dscal(2,x[0])
print(y)
print(x)

[2.2 4.4 6. ]
[[1.1, 2.2, 3], [-1, -2.0, -3.0]]


## _dot

In [35]:
x = np.array([1,2,3]) #try  [[1],[2],[3]]
y = np.array([[2],[1],[1]]) #try  [[2],[1],[1]]   
z = blas.ddot(x, y)
print(z)

7.0


In [40]:
x = np.array([1,2,3]) #try  [[1],[2],[3]]
y = np.array([[2],[1],[1]]) #try  [[2],[1],[1]]   
z = blas.ddot(x, y)
print(z)

7.0


https://numpy.org/doc/stable/reference/generated/numpy.dot.html

In [41]:
z = np.dot(x, y)
print(z)

[7]


In [77]:
n = 5000
x = np.random.rand(n)
y = np.random.rand(n)

In [78]:
%timeit z = blas.ddot(x, y)

1.77 µs ± 35.1 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [79]:
%timeit z = np.dot(x, y)

3.6 µs ± 186 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [80]:
%timeit z = np.vdot(x, y)

3.5 µs ± 261 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


Обратите внимание на разницу *cdotu* и *cdotc* в документации

## _nrm2

In [89]:
x = np.array([2,-2,1])  #try [[2],[-2],[1]]

xn = blas.dnrm2(x)
print(xn)

3.0


numpy.linalg.norm

https://numpy.org/doc/stable/reference/generated/numpy.linalg.norm.html   

scipy.linangl

https://docs.scipy.org/doc/scipy/reference/linalg.html

In [90]:
xn = sp.linalg.norm(x,1)
print(xn)
xn = np.linalg.norm(x,1)
print(xn)

5.0
5.0


In [95]:
n = 3000
x = np.random.rand(n)

In [92]:
%timeit xn = blas.dnrm2(x)

1.15 µs ± 31.6 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [96]:
%timeit xn = sp.linalg.norm(x)

7.03 µs ± 192 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [97]:
%timeit xn = np.linalg.norm(x)

5.03 µs ± 172 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


# BLAS Level 2

Операции матрица-вектор

**_gemv** - умножение матрицы на вектор и скаляр:  *aAx* (a - скаляр, A - матрица, x - вектор)

**_trmv** - умножение треугольной матрицы на вектор: *Lx*

**_trsv** - решение СЛАУ с нижней треугольной матрицей: *inv(L)x*



## _gemv

In [161]:
x = np.array([2,1])  # try [[2],[1]]
A = np.array([[-1,1],[3,2]])
alfa = 2.0

y = blas.dgemv(alfa,A,x)
print(y)

[-2. 16.]


## _trmv

In [160]:
x = np.array([2,1])  # try [[2],[1]]
A = np.array([[-1,3],[1,2]])

y = blas.dtrmv(A,x, lower = 0)
print(y)

[[1.]
 [2.]]


## _trsv

In [173]:
x = np.array([2,1])  # try [[2],[1]]
A = np.array([[-1,3],[1,2]])

y = blas.dtrsv(A,x, lower = 0)
print(y)

[-0.5  0.5]


In [180]:
A = np.array([[1,2,-1.0],[-4,1,2],[3,2,-3]])
b = np.array([2,4,-2])
x = sp.linalg.solve(A, b)
print(x)

[1. 2. 3.]


In [176]:
n = 100
A = np.array(np.random.randn(n,n), order = 'F')
b = np.array(np.random.randn(n))
x = sp.linalg.solve(A, b)

In [177]:
%timeit x = sp.linalg.solve(A, b)

127 µs ± 1.47 µs per loop (mean ± std. dev. of 7 runs, 10000 loops each)


# BLAS Level 3

Операции матрица-матрица

_gemm - умножение матрицы на матрицу общего вида: 

   C := alpha*op( A )*op( B ) + beta*C



In [44]:
A = np.array([[1,2,3],[4,5,6]], order = 'F')
B = np.array([[1,-1],[0,1],[1,1]], order = 'F')
a = 2

C = blas.dgemm(a,A,B)
print(C)

[[ 8.  8.]
 [20. 14.]]
