In [9]:
import numpy as np
import scipy.linalg as sla

In [10]:
#A = np.array([[1, 3, 2, 0], [0, -1, -1, 0], [2, 2, 1, 1], [-1, 1, 3, 4],[-4, 0, 1, -2],[0, -1, -2, 5]])
A = np.array([[1, 3, 2, 0], [0, -1, -1, 0], [2, 2, 1, 1], [-1, 1, 3, 4]])
print(A)
# Slice out the columns of A for processing
A_1 = A[:,0:1]
A_2 = A[:,1:2]
A_3 = A[:,2:3]
A_4 = A[:,3:4]
print(A[:,0:1])

[[ 1  3  2  0]
 [ 0 -1 -1  0]
 [ 2  2  1  1]
 [-1  1  3  4]]
[[ 1]
 [ 0]
 [ 2]
 [-1]]


In [11]:
# Carry out Gram-Schmidt process
U_1 = A_1/sla.norm(A_1)
W_2 = A_2 - np.dot(np.transpose(A_2),U_1)*U_1
U_2 = W_2/sla.norm(W_2)
W_3 = A_3 - np.dot(np.transpose(A_3),U_1)*U_1 - np.dot(np.transpose(A_3),U_2)*U_2
U_3 = W_3/sla.norm(W_3)
W_4 = A_4 - np.dot(np.transpose(A_4),U_1)*U_1 - np.dot(np.transpose(A_4),U_2)*U_2 - np.dot(np.transpose(A_4),U_3)*U_3
U_4 = W_4/sla.norm(W_4)

# Assemble the matrix Q

Q = np.hstack((U_1,U_2,U_3,U_4))
print("Q")
print(np.round(Q,3),'\n')

# Check that Q is orthogonal

print("QTQ")
print(np.round(Q.transpose()@Q),'\n')

# Compute R

R = Q.transpose()@A

#  Check

print("Q")
print(Q,'\n')
print("R")
print(np.round(R,8),'\n')
print("QR")
print(np.round(Q@R))

Q
[[ 0.408  0.667 -0.519  0.346]
 [ 0.    -0.333  0.189  0.924]
 [ 0.816 -0.     0.566 -0.115]
 [-0.408  0.667  0.613  0.115]] 

QTQ
[[ 1. -0.  0.  0.]
 [-0.  1.  0. -0.]
 [ 0.  0.  1. -0.]
 [ 0. -0. -0.  1.]] 

Q
[[ 4.08248290e-01  6.66666667e-01 -5.18544973e-01  3.46410162e-01]
 [ 0.00000000e+00 -3.33333333e-01  1.88561808e-01  9.23760431e-01]
 [ 8.16496581e-01 -1.48029737e-16  5.65685425e-01 -1.15470054e-01]
 [-4.08248290e-01  6.66666667e-01  6.12825877e-01  1.15470054e-01]] 

R
[[ 2.44948974  2.44948974  0.40824829 -0.81649658]
 [-0.          3.          3.66666667  2.66666667]
 [ 0.          0.          1.1785113   3.01698893]
 [ 0.         -0.         -0.          0.34641016]] 

QR
[[ 1.  3.  2. -0.]
 [ 0. -1. -1. -0.]
 [ 2.  2.  1.  1.]
 [-1.  1.  3.  4.]]


In [12]:
def QRFactorization(A):
    

    # Check shape of A
    if (A.shape[0] < A.shape[1]):
        print("A must have more rows than columns for QR factorization.")
        return

    m = A.shape[0]
    n = A.shape[1]
    
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    
    for i in range(n):
        W = A[:,i:i+1]
        for j in range(i):
                W = W - np.dot(np.transpose(A[:,i:i+1]),Q[:,j:j+1])*Q[:,j:j+1]
                # записать scalar в матрицу R
        Q[:,i:i+1] = W/sla.norm(W)
        
    R = Q.transpose()@A
    
    return (Q,R)

In [13]:
def QRFactorization2(A):
    

    # Check shape of A
    if (A.shape[0] < A.shape[1]):
        print("A must have more rows than columns for QR factorization.")
        return

    m = A.shape[0]
    n = A.shape[1]
    
    Q = np.zeros((m,n))
    R = np.zeros((n,n))
    
    for i in range(n):
        W = A[:,i:i+1]
        for j in range(i):
            scalar = np.dot(np.transpose(A[:,i:i+1]),Q[:,j:j+1])
            W = W - scalar*Q[:,j:j+1]
            R[j,i] = scalar
            # записать scalar в матрицу R
        Q[:,i:i+1] = W/sla.norm(W)
        R[i,i] = np.dot(np.transpose(A[:,i:i+1]),Q[:,i:i+1])
    
    #R = Q.transpose()@A
    
    return (Q,R)

In [14]:
[Q,R] =  QRFactorization(A)
[Q2,R2] =  QRFactorization2(A)

In [15]:
print(np.round(Q,3))
print(np.round(R,3))
print(np.round(Q@R))

print(np.round(Q2 - Q,3))
print(np.round(R2 - R,3))
print(np.round(Q2@R2))

[[ 0.408  0.667 -0.519  0.346]
 [ 0.    -0.333  0.189  0.924]
 [ 0.816 -0.     0.566 -0.115]
 [-0.408  0.667  0.613  0.115]]
[[ 2.449  2.449  0.408 -0.816]
 [-0.     3.     3.667  2.667]
 [ 0.     0.     1.179  3.017]
 [ 0.    -0.    -0.     0.346]]
[[ 1.  3.  2. -0.]
 [ 0. -1. -1. -0.]
 [ 2.  2.  1.  1.]
 [-1.  1.  3.  4.]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[ 0.  0.  0.  0.]
 [ 0.  0.  0.  0.]
 [-0. -0. -0.  0.]
 [-0.  0.  0.  0.]]
[[ 1.  3.  2. -0.]
 [ 0. -1. -1. -0.]
 [ 2.  2.  1.  1.]
 [-1.  1.  3.  4.]]
